### ISSUE TITLE
Traverse and Terrestria Trees

### ISSUE THREAD

**Issue by pjlasl** [grondag/trees-dont-float#15]
Could you make your mod compaticle with these two Fabric mods? Traverse and Terrestria. They have a lot of trees in their biomes.
I tried different axes on their trees and they do not chop down like the minecraft trees.

**Comment by grondag** [comment]
Yes, I love those mods and TDNF used to be compatible.  I'll have a look.

**Comment by grondag** [comment]
Unable to reproduce with TDNF 1.10.90, Cinderscapes 1.0.4-build25, Terrestria 2.0.3-build46 and Traverse 2.2.12-build24.  I tried with diamond and iron axes and in creative.

If able to provide reproducible steps, please reopen.

**Comment by leo60228** [comment]
With:
* TDNF 1.10.90
* Terrestria 2.0.3+build.46
* Traverse 2.2.13+build.27

This doesn't work. I can send a MultiMC instance export if it would help.

**Comment by leo60228** [comment]
This doesn't apply to all mods, for what it's worth. Tech Reborn ones are fine.

**Comment by grondag** [comment]
MultiMC instance would indeed help.

**Comment by leo60228** [comment]
How should I send it to you?

**Comment by grondag** [comment]
Good question. I don’t have anything set up? Google docs or Dropbox maybe?

**Comment by leo60228** [comment]
https://drive.google.com/file/d/1_1zD5gbJYVHGbFnHYmIi-KS1E2reDoLO/view?usp=sharing

**Comment by pjlasl** [comment]
The traverse and Terrestria modders added a new mod called Cinderscapes for the Nether and it would be great if you could make this compatible with that also.

**Comment by grondag** [comment]
@leo60228 I've loaded up the pack you provided (thanks!) and... it works great!

I tried chopping down several kinds of non-vanilla trees with different combinations of axes and settings, and it gave me no problems.

I absolutely believe it isn't working for you, but the reason still isn't clear.

There are a couple things you can check, but I doubt they are the issue:

1. Make sure the trees aren't connected to other trees anywhere.
2. If your axe is damaged then it may not work because the default settings use tool durability *and* protect tools from breaking.  If you don't want those mechanics they can be turned off in the config.

Another long-shot thing you can check:  look at a naturally-generated log (not a log you placed) with F3 debug enabled and look at the lower right screen under "Targeted Block".  Do you see text that reads "persistent: true"?

If so, then somehow your world is generating or changing log blocks so that TDNF think they were placed by a player and shouldn't be felled.

I don't know *how* that would be happening, but worth a check.

**Comment by leo60228** [comment]
"Make sure the trees aren't connected to other trees anywhere." Now that
you mention it... I think it might just be as simple as Traverse/Terrestria
trees being connected more often than vanilla ones. I manually cleared all
of the trees around a Terrestria tree and it worked for the remaining one.
Would there be some way to make the check for whether trees are connected
more conservative?

**Comment by grondag** [comment]
@pjlasl All my testing shows that Cinderscapes trees work fine (TDNF doesn't break the fungal "leaves" by design, at least not yet, because they don't naturally decay in vanilla.)

**Comment by grondag** [comment]
> Would there be some way to make the check for whether trees are connected
more conservative?

Probably, yes.  I'll have a look.

**Comment by grondag** [comment]
From CF:
The ones I've had problems with are Japanese Maple and Rainbow Eucalyptus from the Terristria. But I've noticed tonight that sometimes it works. For the Japanese Maple if I cut up to a 4 way branch split then the tree will drop and the Rainbow Eucalyptus the 2x2 truck doesn't trigger the tree to fall but sometimes cutting up to a branch branch will trigger the branch to drop.

**Comment by grondag** [comment]
Appears to be much more reliable in V2.0. (Release coming soon.)
