### ISSUE TITLE
Crash when player breaks wood blocks from house

### ISSUE THREAD

**Issue by calloatti** [grondag/trees-dont-float#2]
https://paste.ee/p/Of9Li

This is an open to lan game, and the other player was choping wood blocks from a house.

**Comment by grondag** [comment]
Thank you for the report.  Trying to get my mods updated to 1.14.3 and am hitting some strange roadblocks.  Will look in this after.

**Comment by rtester47** [comment]
could you do a forge versions?

**Comment by grondag** [comment]
A Forge version from me is unlikely - I find Fabric easier to work with for the types of mods I do. 

However, the mod is licensed as Apache and anyone who wants to  port and maintain a Forge version would be welcome to do so.

**Comment by rtester47** [comment]
I can't wait for the 1.14.3 version to come out I love how the trees fall and become blocks not just become enties you just pick up.  BTW I tried looking for fabric modding tutorials but could not find any where did you go to learn fabric modding?

**Comment by grondag** [comment]
I'm really glad you like it and appreciate you for saying so. I should have a 1.14.3 update out "soon."

I started MC modding with Forge back in 1.7.10 and it was very slow at first because Minecraft is a big, complex system.  Fabric does not have any many tutorials currently but makes fewer changes to the Mojang code, which I find to make it simpler overall.

My advice for learning is to look for simple, open source mods that interest you and clone their code and experiment with them.  All of my mods are open source in part because having mod source code to look at was super helpful to me and I want to pay it forward.

**Comment by grondag** [comment]
Was unable to reproduce but added checks that should prevent it.

**Comment by rtester47** [comment]
Thanks for the 1.4.3 update it seems to work like a charm.

**Comment by grondag** [comment]
Glad to hear it.  Thanks for letting me know.
