### ISSUE TITLE
[Suggestions/Possible Bug] Regarding 2.0's new features

### ISSUE THREAD

**Issue by MechanosG** [grondag/trees-dont-float#24]
I got around to giving 2.0.121 a try.  I like the new features.  I also noticed a few oddities I'd like to ask about.

1.  When using a slow cutting speed and having only 1 log break at a time (with keep logs intact disabled), the first log in the job is instantly cut the moment you finish cutting the bottom log by hand.  So 2 logs end up breaking at once, then it continues with 1 log at a time (or whatever setting you're using).  That first cut ends up looking funny, and happens every time.  Delaying the job by whatever the delay setting is before making the first job cut, could possibly fix it? (For example, if your chop speed is 2 blocks a second, wait half a second before starting the cut job and the cut will theoretically be timed perfectly after the player cut log?)

2.  When using keep logs intact, you can't turn off leaf decay, but I would like to turn it off (I'm using Tiny Tweaks for sped up natural leaf decay, and my idea is to have Trees Don't Float knock the logs down to the ground for easier cutting while the majority of leaves remain in the air for a bit instead of exploding).  Would this be possible in a future update?  I'm keeping in mind there's probably an important reason fast leaf decay is force enabled in this scenario.

3.  When using keep logs intact, I'm noticing some the falling logs are getting desynced and will stay invisible 'till I place or break a nearby block.  I don't think I noticed this happening before 2.0.  Is this a new bug?  I did my testing in a singleplayer world.

**Comment by Danklor** [comment]
In regard to #3 above, I also experience desync when keeping logs intact. In addition, most likely with larger trees, often some logs are completely lost. (e.g. a tree with 10 logs might have 10 logs fall to the ground or it might have 9 or less logs fall to the ground.) In my test world I only used MC 1.16.4, Fabric Loader 0.11.0, Fabric API 0.29.3+1.16, TDNF 2.1.128, and Mod Menu 1.14.13+build.19.

**Comment by grondag** [comment]
I understand the first point but it's somewhat subjective which way is better and at this time I don't feel the extra work to add this as a config option is worthwhile.  The slow cutting speeds are meant to be a performance option vs a gameplay mechanic.  Maybe I will rethink that if there's a lot of interest from the community.

Regarding keep logs intact and leaf decay - intact logs must break leaves because otherwise they would have no place to move.  Intact logs are entities and collide with blocks just like other entities.  It is theoretically possible to have them move through leaves with special-case handling but it's a hack I'd rather not maintain and doesn't fit the spirit of the keep logs intact option.

The desync issues and missing logs with intact falling logs should be much improved in V3.
