### ISSUE TITLE
Cant get rid of mod

### ISSUE THREAD

**Issue by TheRussianBoi1009** [grondag/trees-dont-float#26]
So i checked my mod file and also actual file in my computer for this mod and found nothing, I have also went to curseoforge and deleted everything about this mod, but for some reason, it is still in my game. i want to turn it off and get rid of it but nothing is working, help

**Comment by spiralhalo** [comment]
Are you perhaps playing in a server that runs this mod? This mod can run in the server without client side installation.

Otherwise please answer these questions so we can help you better:
- what launcher are you using?
- how did you download the mod? did you download it manually or through a launcher, or a modpack?

**Comment by TheRussianBoi1009** [comment]
> Are you perhaps playing in a server that runs this mod? This mod can run in the server without client side installation.
> 
> Otherwise please answer these questions so we can help you better:
> 
> * what launcher are you using?
> * how did you download the mod? did you download it manually or through a launcher, or a modpack?

I'm using fabric from cursefordge, this occurs in singleplayer so its not because of the server, and I downloaded the mod through cursefordge launcher

**Comment by spiralhalo** [comment]
I see. Unfortunately I have never used the curseforge launcher so I can't help you with this issue.

**Comment by TheRussianBoi1009** [comment]
> I see. Unfortunately I have never used the curseforge launcher so I can't help you with this issue.

So now, all I can do is have the mod installed and active in my game 247, as you cannot also turn it off?

**Comment by spiralhalo** [comment]
This sounds like an issue with curseforge launcher. You should look up if someone else had the same issue with the launcher or wait for someone who uses the launcher see this issue. I only ever play with MultiMC and GDLauncher so I can't help, that's all.

**Comment by grondag** [comment]
TDNF has no way to remain active when it has been uninstalled. It is literally impossible for it to do so. Not does it have anything in it to avoid being uninstalled. Either the jar is in the mods folder or it is not.

If it is still active in single player then your launcher is still finding it somewhere, somehow. It’s not a problem caused by TDNF.
